services:
  # BASE DE DATOS
  mongo-db:
    container_name: ${MONGO_DB_NAME}
    image: mongo:6.0
    volumes:
      - ./poke-db-vol:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - 27017:27017 # SI OMITIMOS EL PUERTO LA CONEXION NO SE ENCUENTRA EXPUESTA A LAS PERSONAS
    restart: always
    command: ['--auth']


  # MANEJADOR DE BASE DE DATOS
  mongo-express:
    container_name: ${MONGO_EXPRESS_NAME}
    image: mongo-express:1.0-20-alpine3.19
    depends_on:
      - mongo-db
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_USERNAME}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=${MONGO_DB_NAME}
    restart: always


  # BACKEND
  poke-app-backend:
    container_name: 'poke-backend'
    image: klerith/pokemon-nest-app:1.0.0
    depends_on:
      - mongo-db
    ports:
      - 3001:3000
    environment:
      - MONGODB=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_DB_NAME}:27017
      - DB_NAME=${MONGO_DB_NAME}
    restart: always


volumes:
  poke-vol:
    external: false